TOKEN = "8338583447:AAEbRQZQM6ILrD_tYdFtCtbr1yGRpyl-N_s"
ADMIN_ID = 6689435577
FORCE_CHANNEL = "@iIl337"
FORCE_CHANNEL_LINK = "https://t.me/iIl337"
BOT_USERNAME = "FI7O_BOT"
DB_NAME = "bot_data.db"

# القنوات الافتراضية (سيتم تعيينها تلقائيًا إذا لم تكن موجودة)
DEFAULT_SERIES_CHANNEL = "@FIL2360"
DEFAULT_MOVIES_CHANNEL = "@FIL360"
DEFAULT_RECOMMENDATIONS_CHANNEL = "@TOSI7"
